version: '3'
services:
  app:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  # pgadmin:
  #     container_name: pgadmin4
  #     image: dpage/pgadmin4
  #     restart: always
  #     environment:
  #       PGADMIN_DEFAULT_EMAIL: admin@email.com
  #       PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
  #     ports:
  #       - 5050:80
